apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cinemaster.fullname" . }}-data
  labels:
    io.kompose.service: mysql-data
  {{- include "cinemaster.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.data.storageRequest | quote }}