apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cinemaster.fullname" . }}-frontend-claim0
  labels:
    io.kompose.service: frontend-claim0
  {{- include "cinemaster.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.frontendClaim0.storageRequest | quote }}