apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cinemaster.fullname" . }}-mysql-config
  labels:
    io.kompose.service: mysql-config
  {{- include "cinemaster.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.mysqlConfig.storageRequest | quote }}