version: '3.8'
services:
  frontend:
    build: ./frontend
    command: sh -c "npm start"
    ports:
      - 4200:4200
    volumes:
      - ./:/app
      - /node_modules

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/cinemaster
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=mysql -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"

  mysqlserver:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=cinemaster
      - MYSQL_USER=cinemaster
      - MYSQL_DATABASE=cinemaster
      - MYSQL_PASSWORD=cinemaster
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config:
  node_modules: