apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\AloiAl\Desktop\cinemaster\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\AloiAl\Desktop\cinemaster\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - args:
            - ./mvnw
            - spring-boot:run
            - -Dspring-boot.run.profiles=mysql
            - -Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
          env:
            - name: MYSQL_URL
              value: jdbc:mysql://mysqlserver/cinemaster
            - name: SERVER_PORT
              value: "8080"
          image: alfral/cinemaster_backend
          name: backend
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: backend-claim0
      restartPolicy: Always
      volumes:
        - name: backend-claim0
          persistentVolumeClaim:
            claimName: backend-claim0
status: {}
