apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\AloiAl\Desktop\cinemaster\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqlserver
  name: mysqlserver
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mysqlserver
status:
  loadBalancer: {}
