apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\AloiAl\Desktop\cinemaster\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqlserver
  name: mysqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqlserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\AloiAl\Desktop\cinemaster\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mysqlserver
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: cinemaster
            - name: MYSQL_PASSWORD
              value: cinemaster
            - name: MYSQL_ROOT_PASSWORD
              value: cinemaster
            - name: MYSQL_USER
              value: cinemaster
          image: alfral/mysql
          name: mysqlserver
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
            - mountPath: /etc/mysql/conf.d
              name: mysql-config
      restartPolicy: Always
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
        - name: mysql-config
          persistentVolumeClaim:
            claimName: mysql-config
status: {}
